### ISSUE TITLE
Update links to new HICN documentation landing page

### ISSUE THREAD

**Issue by muscariello** [FDio/site#122]
We have moved the documentation landing page to https://hicn.readthedocs.io/en/latest/
which is automatically built by the readthedocs platform.

The platforms builds docs from all tags found in https://github.com/FDio/hicn
starting from tag 22.02 e.g. https://hicn.readthedocs.io/en/v22.02-rc0/

**Comment by edwarnicke** [comment]
@muscariello You could push a PR to fix it here:

https://github.com/FDio/site/blob/373ea8e5011d3c3ed5b0bafcddadb400f8859259/content/documentation/hicn.md?plain=1#L15

**Comment by muscariello** [comment]
@sknat @msardara we could also use S3 as landing pages but it requires additional work.
#123 removes the old documentations and creates redirections which we can also update. 
I did not update the HICN summary page yet.

**Comment by muscariello** [comment]
@msardara  I remove the redirect to 22.06 as readthedocs includes a side bar with all releases built from there.
Hence #123 just updates links to the latest release. The summary page points to a redirect to readthedocs. When we have S3 ready we just need to update that redirect. We need to decided if we want to keep all previous doc releases. In that case we need to update the summary page.

**Comment by msardara** [comment]
Once we push on s3 it makes sense to keep all the releases I think we will get the links in this form:

https://s3-docs.fd.io/hicn/22.02
https://s3-docs.fd.io/hicn/22.06
...

That just need to append in the summary page.

**Comment by muscariello** [comment]
In theory yes. In practice there need to be real updates on the docs :-)

**Comment by muscariello** [comment]
@edwarnicke we may want to wait https://gerrit.fd.io/r/c/ci-management/+/36010 is merged and double check the landing page on S3. In that case I'll update this PR with S3 for good.

**Comment by Neilblaze** [comment]
@edwarnicke, @muscariello apologies for tagging over here directly. I'm redirecting from [here](https://wiki.lfnetworking.org/display/LN/LFN+Mentorship+project+for+FD.io+web+site+UX+Improvements#:~:text=python%20scripting%20language-,Expected%20Outcome,-FD.Landing%20Page) & I just wanted to know the exact repo where LFN participants can potentially contribute?

I'm confused between [`FDio/site`](https://github.com/FDio/site) & [`FDio/hicn`](https://github.com/FDio/hicn) 😅 
Also, I do want to connect to [Dave](https://wiki.lfnetworking.org/display/LN/LFN+Mentorship+project+for+FD.io+web+site+UX+Improvements#:~:text=here%20to%20apply-,Dave%20Wallace%2C%20Cisco,-Maciek%20Konstantynowicz%2C%20Cisco) & [Maciek](https://wiki.lfnetworking.org/display/LN/LFN+Mentorship+project+for+FD.io+web+site+UX+Improvements#:~:text=Maciek%20Konstantynowicz%2C%20Cisco) and discuss about my proposal for [LFN'23](https://wiki.lfnetworking.org/display/LN/LFN+Mentorship+project+for+FD.io+web+site+UX+Improvements) application, but the slack invite link to the community isn't working (refer to: #140). I'd be highly obliged if anyone of you can guide me forward :)

Thanks!
