### ISSUE TITLE
VPP documentation, broken links

### ISSUE THREAD

**Issue by muscariello** [FDio/site#125]
The sphinx build must have something broken as some links point to a different release instead of the current one.

For instance:

https://s3-docs.fd.io/vpp/22.06/gettingstarted/progressivevpp/interface.html

Links point to non existant pages related to 17.04 or 21.06.

**Comment by dwallacelf** [comment]
Thanks for the report.  Fixed by https://gerrit.fd.io/r/c/vpp/+/36505
