### ISSUE TITLE
Proposed front page text change

### ISSUE THREAD

**Issue by edwarnicke** [FDio/site#13]
@nealtex01 suggested the attached text change to the front page, thoughts?

[fd.io home page messaging.pdf](https://github.com/FDio/site/files/3291719/fd.io.home.page.messaging.pdf)

**Comment by muscariello** [comment]
In my opinion there is one component that seems not very well represented which is the transport layer. E.g. the ability to develop transport protocols in user space that can also be very efficient. 
I may also say that the transport layer is where the Linux kernel is harder to upgrade. It is very difficult to see new transport protocols in the Linux kernel. It becomes very simple using VPP. 

To me this is a compelling argument to adopt VPP.

**Comment by edwarnicke** [comment]
@muscariello Could you suggest how we might do so?  I like the idea, just need some input on phrasing :)

@florincoras do you have any thoughts?

**Comment by muscariello** [comment]
I have ideas. Before proposing actual text I’d need to know the current roadmap on TCP, QUIC support. 
If someone can point me to fresh data on that.
I’d like to invite cutting edge innovators to actually implement their own transport here and stop wasting time in the kernel.

**Comment by edwarnicke** [comment]
@nealtext01 - have a look at #14 (@jadenisco is on vacation next week, so figure I'd pitch in :) ).

You can see the preview [here](https://deploy-preview-14--fdio.netlify.com/).  I think I got the text as you provided, but feel like we could use a bit of work on the font and other fine details, thoughts?

**Comment by edwarnicke** [comment]
@muscariello One of the nice things about doing this as Github is we can evolve :)  If you find out what you need before this change goes in, we can incorporate it.  If not, we can do it as another change and review it then :)  Nothing is ever set in stone.

**Comment by edwarnicke** [comment]
@nealtext01 - have a look at #15  (@jadenisco is on vacation next week, so figure I'd pitch in :) ).

You can see the preview [here](https://deploy-preview-15--fdio.netlify.com/). I think I got the text as you provided, but feel like we could use a bit of work on the font and other fine details, thoughts?

**Comment by florincoras** [comment]
@edwarnicke @muscariello I'm definitely fine with mentioning that the session layer is pluggable from transport protocol perspective. Albeit, I don't know how to better phrase it beyond that. For more info on the stack check [this](https://wiki.fd.io/view/VPP/HostStack) and for more info on how the stack has evolved over the past releases, you can either check the [release notes](https://git.fd.io/vpp/tree/RELEASE.md) or the [release plans](https://wiki.fd.io/view/VPP#Previous_Release_Plans) on the wiki page.

**Comment by edwarnicke** [comment]
@nealtx01 - you did an excellent job with the current text... any thoughts on how we might work in the transport level?

**Comment by nealtex01** [comment]
Hey Ed,

Responded earlier this am directly in Github.  Hopefully you received a notification?

Neal

**Comment by edwarnicke** [comment]
@nealtex01 You responded in the right place.  I responded there (with an update to the PR and the preview).

**Comment by edwarnicke** [comment]
@florincoras @muscariello Have a look at PR #15 and see if that incorporates your concerns about transport layer :)
