### ISSUE TITLE
Quick Review of proposed front page

### ISSUE THREAD

**Issue by JDiGiglio** [FDio/site#17]
Hi Ed,

I will need additional time to due this review justice.  Specifically we need to update the message to support the scalability and feature richness.  Right now only fast and it's "time" analogy is in place.

A few additional suggested edits from quick review:
Right at the top, change FD.IO to FD.io to reflect project name.
Change in dialog box to get to the projects to "FD.io projects" as "The" is not necessary.
Logo looks faded.  Chase down high resolution one from Jill.
Not comfortable with "The future of packet processing.  Now."   What about "The future of packet processing is here!"

**Comment by edwarnicke** [comment]
@JDiGiglio I've fixed this in PR #15 - lets continue the conversation over there (at least until its merged).

**Comment by edwarnicke** [comment]
@JDiGiglio "The future of packet processing. Now." vs "The future of packet processing is here!" I'm going to leave to you and @nealtx01 to settle between you (its literally a your language vs his... I figure you will find synergy :) ).  If we could continue the conversation on the PR #15 would be very helpful :)
